name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: cd client && npm ci
    
    - name: Install server dependencies
      run: cd server && npm ci
    
    - name: Build client
      run: cd client && npm run build
    
    - name: Build server
      run: cd server && npm run build
    
    - name: Run client linting
      run: cd client && npm run lint
      
    # Uncomment when tests are added
    # - name: Run tests
    #   run: npm test
